# Javascript Node CircleCI 2.0 configuration file

defaults: &defaults
  docker:
      - image: circleci/openjdk:8u171-jdk-node-browsers
      - image: circleci/mongo:4.2

  working_directory: ~/mernolithic

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          name: Restore backend/general packages
          keys:
            - v1-dependencies-{{.Branch}}-{{ checksum "package.json" }}
            - v1-dependencies-{{.Branch}}-
            - v1-dependencies-

      - run: 
          name: Install backend and general dependencies
          command: npm install

      - save_cache:
          name: Save backend/general packages cache
          paths:
            - ~/.cache/node_modules
          key: v1-dependencies-{{.Branch}}-{{ checksum "package.json" }}
      
      - restore_cache:
          name: Restore frontend packages
          keys:
            - v1-dependencies-{{.Branch}}-{{ checksum "client/package.json" }}
            - v1-dependencies-{{.Branch}}-
            - v1-dependencies-
      
      - run:
          name: Install frontend packages
          command: cd client && npm install
      
      - save_cache:
          paths:
            - ~/.cache/node_modules
          key: v1-dependencies-{{.Branch}}-{{ checksum "client/package.json" }}
      
      - run:
          name: Run backend
          command: npm run backend
          background: true

      - run: 
          name: Run frontend
          command: npm run build-frontend

      - persist_to_workspace:
          root: ~/
          paths:
            - mernolithic
            - .cache

  js_unit_tests:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run: 
          command: |
            cd client
            npm run test  

  backend_unit_tests:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run: 
          name: Backend Unit Tests
          command: npm run backend-unit-tests
  
  ui_tests:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Run backend
          command: npm run backend
          background: true

      - run: 
          name: Run frontend
          command: npm run frontend
          background: true

      - run: 
          name: Run UI tests 
          command: npm run ui-tests 

  api_tests:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run: 
          name: Start backend
          command: npm run backend
          background: true
      - run:
          name: Run local API tests
          command: yarn wait-on http://localhost:3001 && npm run api-tests

workflows:
  version: 2
  starter-workflow:
    jobs:
      - build
      - js_unit_tests:
          requires:
            - build
      - backend_unit_tests:
          requires:
            - build
      - api_tests:
          requires:
            - build
      - ui_tests:
          requires:
            - build